[theme]
primaryColor = "#15803d"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#18181b"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
maxUploadSize = 20
